spring:
  application:
    name: user-mgmt-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/resource_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8081}

app:
  jwt:
    secret: qXjYpZmVcDbWnFkLgHsIrOtUeQxSzAaBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789+/ABCDEF
    expiration: 86400000 # 24 hours

logging:
  level:
    com.resourcemanagement: INFO
    org.springframework.security: DEBUG